# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alex's Blog
email: alexander@bazarov.dev
description: >- # this means to ignore newlines until next section
  Personal blog with projects and notes. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bazarov.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bazarovdev

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true

collections:
  tech_projects:
    output: true

  # - name: Yocto Layer for Klipper
  #   url: https://github.com/bazarovdev/meta-klipper
  # - name: Project 2
  #   url: /project2/
  # - name: Project 3
  #   url: /project3/

just_the_docs:
  # Define which collections are used in just-the-docs
  ga_tracking: G-1D0S99KRGN
  ga_tracking_anonymize_ip: true
  math: katex
  collections:
    tech_projects:
      permalink: "/:collection/:path/"
      # Give the collection a name
      name: "Tech Projects"
      output: true
      toc: true

kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
